/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;

/**
 *
 * @author juren
 */
public class Facture extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Facture.class.getName());

    /**
     * Creates new form Facture
     */
    public Facture() {
        initComponents();
        initSpinners();
         tel_util.addKeyListener(new java.awt.event.KeyAdapter() {
        @Override
        public void keyTyped(java.awt.event.KeyEvent e) {
        char c = e.getKeyChar();

        // Autoriser uniquement chiffres
        if (!Character.isDigit(c)) {
            e.consume();
        }

        // Limite à 10 chiffres
        if (tel_util.getText().length() >= 11) {
            e.consume();
        }
    }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nom_util = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tel_util = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        riz = new javax.swing.JCheckBox();
        sucre = new javax.swing.JCheckBox();
        farine = new javax.swing.JCheckBox();
        haricot = new javax.swing.JCheckBox();
        semoule = new javax.swing.JCheckBox();
        huile = new javax.swing.JCheckBox();
        pain = new javax.swing.JCheckBox();
        riz_qte = new javax.swing.JSpinner();
        sucre_qte = new javax.swing.JSpinner();
        farine_qte = new javax.swing.JSpinner();
        haricot_qte = new javax.swing.JSpinner();
        semoule_qte = new javax.swing.JSpinner();
        huile_qte = new javax.swing.JSpinner();
        pain_qte = new javax.swing.JSpinner();
        savon = new javax.swing.JCheckBox();
        sel = new javax.swing.JCheckBox();
        lotion = new javax.swing.JCheckBox();
        tomate = new javax.swing.JCheckBox();
        arachide = new javax.swing.JCheckBox();
        vin = new javax.swing.JCheckBox();
        biere = new javax.swing.JCheckBox();
        savon_qte = new javax.swing.JSpinner();
        sel_qte = new javax.swing.JSpinner();
        lotion_qte = new javax.swing.JSpinner();
        tomate_qte = new javax.swing.JSpinner();
        arachide_qte = new javax.swing.JSpinner();
        vin_qte = new javax.swing.JSpinner();
        biere_qte = new javax.swing.JSpinner();
        allumette = new javax.swing.JCheckBox();
        cure_dent = new javax.swing.JCheckBox();
        piment = new javax.swing.JCheckBox();
        whisky = new javax.swing.JCheckBox();
        poulet = new javax.swing.JCheckBox();
        sardine = new javax.swing.JCheckBox();
        corned_beef = new javax.swing.JCheckBox();
        allumette_qte = new javax.swing.JSpinner();
        cure_dent_qte = new javax.swing.JSpinner();
        piment_qte = new javax.swing.JSpinner();
        whisky_qte = new javax.swing.JSpinner();
        poulet_qte = new javax.swing.JSpinner();
        sardine_qte = new javax.swing.JSpinner();
        corned_beef_qte = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        Acheter = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        facture_area = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nom :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tel :");

        riz.setText("Riz 2000fc/Kg");
        riz.addActionListener(this::rizActionPerformed);

        sucre.setText("Sucre 3800fc/Kg");
        sucre.addActionListener(this::sucreActionPerformed);

        farine.setText("Farine 3000fc/Kg");
        farine.addActionListener(this::farineActionPerformed);

        haricot.setText("Haricot 2500fc/Kg");
        haricot.addActionListener(this::haricotActionPerformed);

        semoule.setText("Semoule 2500fc/Kg");
        semoule.addActionListener(this::semouleActionPerformed);

        huile.setText("Huile 1500fc/L");
        huile.addActionListener(this::huileActionPerformed);

        pain.setText("Pain 1500fc/Pc");
        pain.addActionListener(this::painActionPerformed);

        savon.setText("Savon 2000fc/Pc");
        savon.addActionListener(this::savonActionPerformed);

        sel.setText("Sel 1500fc/Kg");
        sel.addActionListener(this::selActionPerformed);

        lotion.setText("Lotion 4500fc/Pc");
        lotion.addActionListener(this::lotionActionPerformed);

        tomate.setText("Tomate 200fc/Pc");
        tomate.addActionListener(this::tomateActionPerformed);

        arachide.setText("Arachide 1500fc/Kg");
        arachide.addActionListener(this::arachideActionPerformed);

        vin.setText("Vin 45000fc/Pc");
        vin.addActionListener(this::vinActionPerformed);

        biere.setText("Biere 2500fc/Pc");
        biere.addActionListener(this::biereActionPerformed);

        allumette.setText("Allumette 300fc/Pc");
        allumette.addActionListener(this::allumetteActionPerformed);

        cure_dent.setText("Cure dent 300fc/Pc");
        cure_dent.addActionListener(this::cure_dentActionPerformed);

        piment.setText("Piment 50fc/Pc");
        piment.addActionListener(this::pimentActionPerformed);

        whisky.setText("Whisky 20000fc/Pc");
        whisky.addActionListener(this::whiskyActionPerformed);

        poulet.setText("Poulet 2500fc/Pc");
        poulet.addActionListener(this::pouletActionPerformed);

        sardine.setText("Sardine 2000fc/Pc");
        sardine.addActionListener(this::sardineActionPerformed);

        corned_beef.setText("Corned Beef 4500fc/Pc");
        corned_beef.addActionListener(this::corned_beefActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(riz)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(riz_qte, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(pain)
                        .addGap(28, 28, 28)
                        .addComponent(pain_qte, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(sucre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sucre_qte, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(farine)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(haricot)
                            .addComponent(semoule)
                            .addComponent(huile))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(huile_qte, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(semoule_qte, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(haricot_qte, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(farine_qte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(savon)
                                .addGap(18, 18, 18)
                                .addComponent(savon_qte, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(sel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sel_qte, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(cure_dent)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cure_dent_qte, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(allumette)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(allumette_qte, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lotion)
                        .addGap(18, 18, 18)
                        .addComponent(lotion_qte, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(piment)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(piment_qte, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(tomate)
                                .addGap(19, 19, 19)
                                .addComponent(tomate_qte, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(arachide)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(arachide_qte, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vin)
                                    .addComponent(biere))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(vin_qte, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(biere_qte, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(whisky)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(whisky_qte, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(poulet)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(poulet_qte, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(corned_beef)
                                    .addComponent(sardine))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sardine_qte, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(corned_beef_qte, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(riz)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(savon)
                        .addComponent(savon_qte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(allumette)
                        .addComponent(allumette_qte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(riz_qte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sucre)
                        .addComponent(sucre_qte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sel))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cure_dent)
                        .addComponent(sel_qte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cure_dent_qte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(farine)
                        .addComponent(farine_qte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lotion)
                        .addComponent(lotion_qte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(piment)
                        .addComponent(piment_qte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tomate, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(haricot)
                        .addComponent(whisky)
                        .addComponent(whisky_qte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(haricot_qte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tomate_qte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(arachide, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(semoule)
                        .addComponent(semoule_qte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(poulet)
                        .addComponent(poulet_qte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(arachide_qte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(huile)
                    .addComponent(huile_qte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vin)
                    .addComponent(vin_qte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sardine)
                    .addComponent(sardine_qte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pain)
                    .addComponent(pain_qte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(biere)
                    .addComponent(biere_qte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(corned_beef)
                    .addComponent(corned_beef_qte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nom_util, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(tel_util))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nom_util, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tel_util, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Facture");

        Acheter.setBackground(java.awt.Color.red);
        Acheter.setText("Acheter");
        Acheter.addActionListener(this::AcheterActionPerformed);

        facture_area.setColumns(20);
        facture_area.setRows(5);
        jScrollPane2.setViewportView(facture_area);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(140, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Acheter)
                        .addGap(365, 365, 365))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(89, 89, 89))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Acheter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void initSpinners() {
        javax.swing.JSpinner[] spinners = {
            riz_qte, sucre_qte, farine_qte, haricot_qte, semoule_qte, huile_qte, pain_qte,
            savon_qte, sel_qte, lotion_qte, tomate_qte, arachide_qte, vin_qte, biere_qte,
            allumette_qte, cure_dent_qte, piment_qte, whisky_qte, poulet_qte, sardine_qte, corned_beef_qte
        };

    for (javax.swing.JSpinner sp : spinners) {
        sp.setModel(new javax.swing.SpinnerNumberModel(0, 0, 1000, 1));
    }
    }
    private void ajouterArticle(String nom, int qte, double prix) {
    if (qte > 0) {
        double sousTotal = qte * prix;
        facture_area.append(
            String.format("%-15s %5d x %8.2f = %8.2f FC\n",
                    nom, qte, prix, sousTotal)
        );
    }
    }
   

    private void sucreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sucreActionPerformed
        // TODO add your handling code here:
        sucre_qte.setEnabled(sucre.isSelected());
    }//GEN-LAST:event_sucreActionPerformed

    private void huileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_huileActionPerformed
        // TODO add your handling code here:
        huile_qte.setEnabled(huile.isSelected());
    }//GEN-LAST:event_huileActionPerformed

    private void allumetteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allumetteActionPerformed
        // TODO add your handling code here:
        allumette_qte.setEnabled(allumette.isSelected());
    }//GEN-LAST:event_allumetteActionPerformed

    private void rizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rizActionPerformed
        // TODO add your handling code here:
         riz_qte.setEnabled(riz.isSelected());
    }//GEN-LAST:event_rizActionPerformed

    private void farineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_farineActionPerformed
        // TODO add your handling code here:
        farine_qte.setEnabled(farine.isSelected());
    }//GEN-LAST:event_farineActionPerformed

    private void haricotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_haricotActionPerformed
        // TODO add your handling code here:
        haricot_qte.setEnabled(haricot.isSelected());
    }//GEN-LAST:event_haricotActionPerformed

    private void semouleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semouleActionPerformed
        // TODO add your handling code here:
        semoule_qte.setEnabled(semoule.isSelected());
    }//GEN-LAST:event_semouleActionPerformed

    private void painActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_painActionPerformed
        // TODO add your handling code here:
        pain_qte.setEnabled(pain.isSelected());
    }//GEN-LAST:event_painActionPerformed

    private void savonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savonActionPerformed
        // TODO add your handling code here:
        savon_qte.setEnabled(savon.isSelected());
    }//GEN-LAST:event_savonActionPerformed

    private void selActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selActionPerformed
        // TODO add your handling code here:
        sel_qte.setEnabled(sel.isSelected());
    }//GEN-LAST:event_selActionPerformed

    private void lotionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lotionActionPerformed
        // TODO add your handling code here:
        lotion_qte.setEnabled(lotion.isSelected());
    }//GEN-LAST:event_lotionActionPerformed

    private void tomateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tomateActionPerformed
        // TODO add your handling code here:
        tomate_qte.setEnabled(tomate.isSelected());
    }//GEN-LAST:event_tomateActionPerformed

    private void arachideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arachideActionPerformed
        // TODO add your handling code here:
        arachide_qte.setEnabled(arachide.isSelected());
    }//GEN-LAST:event_arachideActionPerformed

    private void vinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vinActionPerformed
        // TODO add your handling code here:
        vin_qte.setEnabled(vin.isSelected());
    }//GEN-LAST:event_vinActionPerformed

    private void biereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biereActionPerformed
        // TODO add your handling code here:
        biere_qte.setEnabled(biere.isSelected());
    }//GEN-LAST:event_biereActionPerformed

    private void cure_dentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cure_dentActionPerformed
        // TODO add your handling code here:
        cure_dent_qte.setEnabled(cure_dent.isSelected());
    }//GEN-LAST:event_cure_dentActionPerformed

    private void pimentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pimentActionPerformed
        // TODO add your handling code here:
        piment_qte.setEnabled(piment.isSelected());
    }//GEN-LAST:event_pimentActionPerformed

    private void whiskyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whiskyActionPerformed
        // TODO add your handling code here:
        whisky_qte.setEnabled(whisky.isSelected());
    }//GEN-LAST:event_whiskyActionPerformed

    private void pouletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pouletActionPerformed
        // TODO add your handling code here:
        poulet_qte.setEnabled(poulet.isSelected());
    }//GEN-LAST:event_pouletActionPerformed

    private void sardineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sardineActionPerformed
        // TODO add your handling code here:
        sardine_qte.setEnabled(sardine.isSelected());
    }//GEN-LAST:event_sardineActionPerformed

    private void corned_beefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corned_beefActionPerformed
        // TODO add your handling code here:
        corned_beef_qte.setEnabled(corned_beef.isSelected());
    }//GEN-LAST:event_corned_beefActionPerformed

    private void AcheterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcheterActionPerformed
        // TODO add your handling code here:
    String nom = nom_util.getText().trim();
    String tel = tel_util.getText().trim();
    facture_area.setText("");

    if (nom.isEmpty() || tel.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Veuillez entrer le nom et le numéro de téléphone",
                "Erreur", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    
    if (!tel.matches("\\d+")) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Le numéro de téléphone doit contenir uniquement des chiffres",
                "Erreur", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    
    if (tel.length() == 11) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Le numéro de téléphone ne doit pas dépasser 10 chiffres",
                "Erreur", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }
       facture_area.append("========= FACTURE =========\n");
    facture_area.append("Client : " + nom + "\n");
    facture_area.append("Téléphone : " + tel + "\n");
    facture_area.append("--------------------------------\n");
    facture_area.append(String.format("%-15s %5s %10s %10s\n", "Article", "Qté", "PU", "Total"));
    facture_area.append("--------------------------------\n");
    
    double totalHT = 0 ;

    if (riz.isSelected()) {
        int qte = (int) riz_qte.getValue();
        double prix = 2000;
        ajouterArticle("Riz", qte, prix);
        totalHT += qte*prix;
    }

    if (sucre.isSelected()) {
        int qte = (int) sucre_qte.getValue();
        double prix = 3800;
        ajouterArticle("Sucre", qte, prix);
        totalHT += qte*prix;
    }

    if (farine.isSelected()) {
        int qte = (int) farine_qte.getValue();
        double prix = 3000;
        ajouterArticle("Farine", qte, prix);
        totalHT += qte*prix;
    }

    if (haricot.isSelected()) {
        int qte = (int) haricot_qte.getValue();
        double prix = 2500;
        ajouterArticle("Haricot", qte, prix);
        totalHT += qte*prix;
    }

    if (semoule.isSelected()) {
        int qte = (int) semoule_qte.getValue();
        double prix = 2500;
        ajouterArticle("Semoule", qte, prix);
        totalHT += qte*prix;
    }

    if (huile.isSelected()) {
        int qte = (int) huile_qte.getValue();
        double prix = 1500;
        ajouterArticle("Huile", qte, prix);
        totalHT += qte*prix;
    }

    if (pain.isSelected()) {
        int qte = (int) pain_qte.getValue();
        double prix = 1500;
        ajouterArticle("Pain", qte, prix);
        totalHT += qte*prix;
    }

    if (savon.isSelected()) {
        int qte = (int) savon_qte.getValue();
        double prix = 2000;
        ajouterArticle("Savon", qte, prix);
        totalHT += qte*prix;
    }

    if (sel.isSelected()) {
        int qte = (int) sel_qte.getValue();
        double prix = 1500;
        ajouterArticle("Sel", qte, prix);
        totalHT += qte*prix;
    }

    if (lotion.isSelected()) {
        int qte = (int) lotion_qte.getValue();
        double prix = 4500;
        ajouterArticle("Lotion", qte, prix);
        totalHT += qte*prix;
    }

    if (tomate.isSelected()) {
        int qte = (int) tomate_qte.getValue();
        double prix = 200;
        ajouterArticle("Tomate", qte, prix);
        totalHT += qte*prix;
    }

    if (arachide.isSelected()) {
        int qte = (int) arachide_qte.getValue();
        double prix = 1500;
        ajouterArticle("Arachide", qte, prix);
        totalHT += qte*prix;
    }

    if (vin.isSelected()) {
        int qte = (int) vin_qte.getValue();
        double prix = 45000;
        ajouterArticle("Vin", qte, prix);
        totalHT += qte*prix;
    }

    if (biere.isSelected()) {
        int qte = (int) biere_qte.getValue();
        double prix = 2500;
        ajouterArticle("Biere", qte, prix);
        totalHT += qte*prix;
    }

    if (allumette.isSelected()) {
        int qte = (int) allumette_qte.getValue();
        double prix = 300;
        ajouterArticle("Allumette", qte, prix);
        totalHT += qte*prix;
    }

    if (cure_dent.isSelected()) {
        int qte = (int) cure_dent_qte.getValue();
        double prix = 300;
        ajouterArticle("Cure dent", qte, prix);
        totalHT += qte*prix;
    }

    if (piment.isSelected()) {
        int qte = (int) piment_qte.getValue();
        double prix = 50;
        ajouterArticle("Piment", qte, prix);
        totalHT += qte*prix;
    }

    if (whisky.isSelected()) {
        int qte = (int) whisky_qte.getValue();
        double prix = 20000;
        ajouterArticle("Whisky", qte, prix);
        totalHT += qte*prix;
    }

    if (poulet.isSelected()) {
        int qte = (int) poulet_qte.getValue();
        double prix = 2500;
        ajouterArticle("Poulet", qte, prix);
        totalHT += qte*prix;
    }

    if (sardine.isSelected()) {
        int qte = (int) sardine_qte.getValue();
        double prix = 2000;
        ajouterArticle("Sardine", qte, prix);
        totalHT += qte*prix;
    }

    if (corned_beef.isSelected()) {
        int qte = (int) corned_beef_qte.getValue();
        double prix = 4500;
        ajouterArticle("Corned beef", qte, prix);
        totalHT += qte*prix;
    }
        
         
    double TVA = totalHT * 0.16;
    double totalTTC = totalHT + TVA;
    double remise = 0;

    if (totalHT >= 220000) {
        remise = totalTTC * 0.30; 
        totalTTC -= remise;
    }

    
    facture_area.append("--------------------------------\n");
    facture_area.append(String.format("Total HT     : %36.2f FC\n", totalHT));
    facture_area.append(String.format("TVA (16%%)    : %36.2f FC\n", TVA));
    if (remise > 0) {
        facture_area.append(String.format("Remise 30%%   : -%34.2f FC\n", remise));
    }
    facture_area.append(String.format("TOTAL TTC    : %36.2f FC\n", totalTTC));
    facture_area.append("==============================\n");

    javax.swing.JOptionPane.showMessageDialog(this,
            "Client : " + nom + "\nTéléphone : " + tel + 
            "\nTOTAL À PAYER : " + totalTTC + " FC",
            "FACTURE", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    
    }//GEN-LAST:event_AcheterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Facture().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Acheter;
    private javax.swing.JCheckBox allumette;
    private javax.swing.JSpinner allumette_qte;
    private javax.swing.JCheckBox arachide;
    private javax.swing.JSpinner arachide_qte;
    private javax.swing.JCheckBox biere;
    private javax.swing.JSpinner biere_qte;
    private javax.swing.JCheckBox corned_beef;
    private javax.swing.JSpinner corned_beef_qte;
    private javax.swing.JCheckBox cure_dent;
    private javax.swing.JSpinner cure_dent_qte;
    private javax.swing.JTextArea facture_area;
    private javax.swing.JCheckBox farine;
    private javax.swing.JSpinner farine_qte;
    private javax.swing.JCheckBox haricot;
    private javax.swing.JSpinner haricot_qte;
    private javax.swing.JCheckBox huile;
    private javax.swing.JSpinner huile_qte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox lotion;
    private javax.swing.JSpinner lotion_qte;
    private javax.swing.JTextField nom_util;
    private javax.swing.JCheckBox pain;
    private javax.swing.JSpinner pain_qte;
    private javax.swing.JCheckBox piment;
    private javax.swing.JSpinner piment_qte;
    private javax.swing.JCheckBox poulet;
    private javax.swing.JSpinner poulet_qte;
    private javax.swing.JCheckBox riz;
    private javax.swing.JSpinner riz_qte;
    private javax.swing.JCheckBox sardine;
    private javax.swing.JSpinner sardine_qte;
    private javax.swing.JCheckBox savon;
    private javax.swing.JSpinner savon_qte;
    private javax.swing.JCheckBox sel;
    private javax.swing.JSpinner sel_qte;
    private javax.swing.JCheckBox semoule;
    private javax.swing.JSpinner semoule_qte;
    private javax.swing.JCheckBox sucre;
    private javax.swing.JSpinner sucre_qte;
    private javax.swing.JTextField tel_util;
    private javax.swing.JCheckBox tomate;
    private javax.swing.JSpinner tomate_qte;
    private javax.swing.JCheckBox vin;
    private javax.swing.JSpinner vin_qte;
    private javax.swing.JCheckBox whisky;
    private javax.swing.JSpinner whisky_qte;
    // End of variables declaration//GEN-END:variables
}
